#spring:
#  thymeleaf:
#    prefix: classpath:/templates/
#    suffix: .html
#    cache: false

spring:    
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://10.51.103.46:5432/dams_dev?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: dams_dev
    password: dams_dev
    
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
    
#spring:
#    datasource:
#        driverClassName: org.postgresql.Driver
#        url:  jdbc:postgresql://10.51.103.46:5432/ZDL_ECPI?useUnicode=true&currentSchema=ZDL_ECPI&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
#        username:  ZDL_ECPI
#        password:  ZDL_ECPI
#        max-idle:  100
#        max-wait:  100000
#        min-idle:  5
#        initial-size:  5
#        validation-query:  SELECT 1
#        test-on-borrow:  true
#        test-while-idle:  true
#        time-between-eviction-runs-millis:  18800
#        jdbc-interceptors:  ConnectionState;SlowQueryReport(threshold=1000)
#    jpa:
#        properties.hibernate.hbm2ddl.auto: update
#        show-sql: false
    